# Generated by Django 5.1.3 on 2024-12-22 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_bookmark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'post')},
        ),
    ]
